apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../default
  - machineDeployment.yaml
  - linodeMachineTemplate.yaml
  - kubeadmConfigTemplate.yaml
patches:
  - target:
      kind: HelmChartProxy
      name: .*-linode-cloud-controller-manager
    patch: |-
      - op: replace
        path: /spec/valuesTemplate
        value: |
          sharedIPLoadBalancing:
            defaultLoadBalancer: cilium-bgp
            bgpNodeSelector: cilium-bgp-peering=true
          routeController:
            vpcName: {{ .InfraCluster.spec.vpcRef.name }}
            clusterCIDR: 10.0.0.0/8
            configureCloudRoutes: true
          secretRef:
            name: "linode-token-region"
          image:
            pullPolicy: IfNotPresent
          env:
            LINODE_URL: https://api.linode.com/v4beta
transformers:
- |
  apiVersion: builtin
  kind: ReplacementTransformer
  metadata:
    name: clone-kubeadmconfig
  replacements:
  - source:
      kind: KubeadmConfigTemplate
      name: ${CLUSTER_NAME}-md-0
      fieldPath: .spec
    targets:
    - select:
        kind: KubeadmConfigTemplate
        name: ${CLUSTER_NAME}-md-bgp
      fieldPaths:
      - .spec
      options:
        create: true
- |-
  apiVersion: builtin
  kind: PatchTransformer
  metadata:
    name: patch-kubeadmconfig
  patch: |-
    - op: add
      path: /spec/template/spec/joinConfiguration/nodeRegistration/kubeletExtraArgs/node-labels
      value: cilium-bgp-peering="true"
  target:
    kind: KubeadmConfigTemplate
    name: .*-md-bgp
